export './auth/pages/signup/pages/signUpPage.dart';
// export './auth/login/pages/signUpPage.dart';
export './widgets/header.dart';
export './widgets/header_back.dart';
export './dashboard/pages/dashboard.dart';
export './home/pages/home.dart';
export './home/widgets/section.dart';
export './category/pages/category.dart';
export '../palette/palette.dart';
export './wallet/pages/wallet.dart';